name: MobileApplication
description: "Uppuveli Beach by DSK - Guest Experience App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client
  dio: ^5.4.0
  
  # Secure storage for tokens
  flutter_secure_storage: ^9.0.0
  
  # State management
  provider: ^6.1.1
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # JSON serialization
  json_annotation: ^4.8.1
  
  # Internationalization
  intl: ^0.19.0
  
  # Other utilities
  path: ^1.9.0
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
